### ISSUE TITLE
TIntProcedure Cannot Be Resolved

### ISSUE THREAD

**Issue by workmaster2n** [aled/jsi-examples#1]
SO Question Here: http://stackoverflow.com/questions/21293856/tintprocedure-cannot-be-resolved

When trying to run either example, I am getting a `TIntProcedure cannot be resolved` error even though I am including the `gnu.trove` jar file.  I noticed `TIntProcedure` is actually in `gnu.trove.procedure`, so maybe I have the wrong version of `trove`?

**Comment by aled** [comment]
You are probably using the wrong version of the gnu trove4j library. Version 1.0 of jsi requires version 2.0.2 of trove4j. It works fine if you follow the instructions I posted here:

http://stackoverflow.com/questions/14251509/r-tree-library-how-to-run

```
git clone https://github.com/aled/jsi-examples.git
cd jsi-examples
mvn package
cd target
unzip jsi-examples-1.0.0-SNAPSHOT-jar-with-dependencies.jar
java -cp .:./classes net.sourceforge.jsi.examples.Contains
```
