### ISSUE TITLE
How to put a large number of points into an RTreee

### ISSUE THREAD

**Issue by tanayun** [aled/jsi-examples#3]
Hi, I'm new to JSI. I have about 1,200,000 nodes with longitude and latitude information. I'm wondering how could I load these nodes into an RTree? Many thanks for your kind reply.

**Comment by aled** [comment]
Rectangles are added in line 40 of this file: https://github.com/aled/jsi-examples/blob/master/src/main/java/net/sf/jsi/examples/Contains.java 

Nodes (ie points as opposed to rectangles) are treated as rectangles with the max x == min x and max y == min y.

Hope this helps.

**Comment by tanayun** [comment]
Many thanks! I added a tiny deviation to both longitude and latitude of
each node to make it a "real" rectangle in my current implement before your
reply. Will use your suggested way of treating nodes as rectangles.

2015-01-15 16:58 GMT+08:00 aled notifications@github.com:

> Closed #3 https://github.com/aled/jsi-examples/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aled/jsi-examples/issues/3#event-219280386.

## 

Best regards,

Tana
